### ISSUE TITLE
[HALON-469] Fix broken tests

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1006]
*Created by: Fuuzetsu*

Most changes were fairly straight forward: our rules has change but
no-one update the tests: some message acks missing, ordering of
structures changed etc.

initial-data-doesn't-error: we now use formulaic pvers and have a test
for initial data using those. Instead of wasting time on trying to
update the test to do something sane with simple strategy, just remove
it

ClusterDeath: Remove the race of halonds being killed before angel had a
chance to start recovery on the node. This allows the node to rejoin
after RC restart every time.

---

Enabling in castor in HALON-470 after this one lands

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
