### ISSUE TITLE
HALON-472: Don't fail node when process isn't restarted due to wrong boot level

### ISSUE THREAD

**Issue by root** [Seagate/halon#1009]
*Created by: nc6*

When a process fails (goes to `Failed` state) the "process-restarted" rule attempts to restart it. This can fail if the cluster is on the wrong boot level. A failed process restart is escalated to a node failure. This results in an (erroneous) node failure when the cluster is on the wrong boot level.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
