### ISSUE TITLE
replicated-log: Notify the clients when consensus doesn't pass a request.

### ISSUE THREAD

**Issue by root** [Seagate/halon#1010]
*Created by: facundominguez*

Fixes the ClusterDeath failures reported in
https://jira.xyratex.com/browse/HALON-469

This is needed for GA.

When the cluster is killed, acceptors sometimes record a decree which replicas didn't record yet. When the cluster is restarted, the replicas try to pass decrees which consensus rejects because it already has a value from before the death. In this case, the replicas discarded the later request without ever notifying the clients.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
