### ISSUE TITLE
HALON-477: Add new RAID device even if it's not removed.

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1012]
*Created by: nc6*

Very simple change; if a drive is replaced before we hear that the RAID device failed, we can just add the new one in and (apparently) we won't get the removal notice. There's no problem if we re-add the old drive either.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
