### ISSUE TITLE
[HALON-476] Don't disconnect HALink on keepalive

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1017]
*Created by: Fuuzetsu*

We don't want to manually disconnect ha_links when we detect keepalive:
we want link disconnecting callback to fire first. This will fire when
process in announced as failed but if we disconnect the link then
announce failure, callback never got a chance to run. Now we just leave
the link lying around, announce process as failed and let the callback
deal with actually calling disconnect.

---

This also closes HALON-475. Was tested by Max to do what's expected.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
