### ISSUE TITLE
[HALON-486] Fix and re-enable scheduler tests.

### ISSUE THREAD

**Issue by root** [Seagate/halon#1027]
*Created by: Fuuzetsu*

For most part, the tests were OK. A lot of the failures seen on Castor
were caused by the tests running longer on AWS, further compounded by
tests being ran multiple times if seed is not specified. I adjust the
number of times scheduler tests are ran based on the times seen on AWS.

Further, fix couple of minor issues with how tests were written: using
`whereIsRemoteAsync` is not always reliable: we can request service
start and ask where it is before it manages to start up.

Fix testRejoinRCDeath test by using the persistent subscription
mechanism. Generally make the tests slightly nicer to look at.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
