### ISSUE TITLE
Halon-487: Implement cardinality in the RG.

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1044]
*Created by: nc6*

This allows specifying at the `Relation` level the desired
number of resources at either end of a relation and using
`G.connect` in place of the various `connectUnique` functions
to correctly specify the relationship. Likewise, `connectedTo`
and `connectedFrom` should now return the appropriate type for
the relationship.

Note that it is not possible to implemeent `ExactlyOne`
semantics.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
