### ISSUE TITLE
[HALON-521] Abort SNS if status check shows FAILED

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1048]
*Created by: Fuuzetsu*

We were checking if SNS was completed (IOS have finished working) but we
were also making the assumption that completed repair means successful
repair. Now we deal with situation where repair completes but could have
failed by reporting to the handler which can choose to send abort
message and terminate itself.

Minor: `setObjectState` removed along with its only user. Pool state is
being set in `completeRepair` anyway, with `applyStateChanges` like it
should be.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
