### ISSUE TITLE
HALON-440: prepare ha_interface for out-of-order delivery.

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1055]
*Created by: qnikst*

* Move routing logic to haskell code.
* Use thread that initialized ha_interface for notifications
  delivery and delivered messages instead of global thread.
* Introduce a datatype that carry all messages callbacks.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
