### ISSUE TITLE
[HALON-548] Implement logging RFC in CEP

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1085]
*Created by: nc6*

Update CEP to use new logging framework.

Changes have been made throughout the stack. I suggest reviewing by commit - in particular, I have deliberately encapsulated most of the "rename" changes in a single commit which can be mostly skipped - we basically change `LoopState` to `RC` in a bunch of places.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
