### ISSUE TITLE
HALON-467: Repair not starting after second drive failure (#1066)

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1091]
*Created by: nc6*

* Add additional debug lines

* Introduce 'RestartSNSOperation' rule.

This is needed for when an SNS operation is in progress as a drive
transitions to FAILED. In this case, we need to abort and then
restart repair.

* HALON-540: store pool repair information before starting repair.

* Re-organise rules in Repair module.

Means we don't have to edit multiple files
if we add new rules.

* HALON-358: Remove allProcessChangesNode rule. (#1064)

This rule is no longer required.

* Do not start rebalance when drives are REPAIRING.

* Revert "HALON-540: store pool repair information before starting repair."

This partially reverts commit c09cec509bca00b408288cc66645e921f6c9450b.

We keep the additional calls to 'unsetPoolRepairStatus'.

* Verify pool device state after starting repair.

* Couple of random fixes (not sure why these are needed).

* Allow 'PAUSED" as a ready state.

This was suggested by Mandar at https://seagate.slack.com/archives/mero/p1478771740000264

* Remove timeout in restart rule.

Given this is waiting for other jobs, just remove this in
its entirety. Doesn't help to have the restart job die but
underlying jobs keep running.

* Allow PAUSED state in other check.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
