### ISSUE TITLE
[HALON-535] Don't run SSPL RaidAdd concurrently

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1095]
*Created by: Fuuzetsu*

It could happen that both replace and failure rules would attempt to add
the same device to an array concurrently. While removing the command
from one rule and not the other would be difficult (to test mostly:
there are multiple code paths and entry points), we can solve it by
introducing a job which does the insertion.

This way both rules are free to run concurrently without any issue or
bad interleaving.

--

untested on cluster

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
