### ISSUE TITLE
HALON-561: drop m0_ha_state_init()/m0_ha_state_fini().

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1099]
*Created by: qnikst*

m0_ha_state_init and HASession interfaces are no longer
needed and will be removed from mero. So halon should no
longer use them. Basically this commit just drops unused code.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
