### ISSUE TITLE
HALON-569: add route and exception handlers in ampq.

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1106]
*Created by: qnikst*

AMPQ library creates background threads in order to handle messages
there. It leads to a problems when exception is rised on connection,
service doesn't see that. As a result service doesn't recreate
connection unless manual keepalive will fail.

Adding exception handler with logging and automatic restart fixes
that problem.

Logging of unroutable messages is also configured.

components: service:sspl-hl, service:sspl.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
