### ISSUE TITLE
HALON-571: Move disk to previous state when SNS operation is aborted.

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1112]
*Created by: qnikst*

Move disk to the state where it was if SNS operation is aborted.
This makes disks not stuck in REPAIRING, REBALANCE states when
SNS operation fails because of IOS failure.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
