### ISSUE TITLE
[HALON-576] Don't accumulate phases in dispatcher

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1124]
*Created by: Fuuzetsu*

There are basically 3 ways to fix this issue:

* The way in the commit: set default state in the first phase

* In CEP: this means a change in behaviour halon-wide and this fix needs
  to be backported to release branch so it's needless risk (HALON-577
  for CEP fix however)

* Fork at rule start: similarly to CEP change, it poses a risk by being
  a much bigger change in behaviour than necessary

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
