### ISSUE TITLE
Add more documentation.

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1137]
*Created by: qnikst*

Add more documentation and implement EQTracker and EQ hierarchies.

EQTracker       - public user facing API
  +--- Internal - hidden types
  +--- Process  - hidden implementation of the EQTracker process and halon
                  internal functions.

EventQueue      - public user facing API
 +---- Producer - hidden internal functions to send messages
 +---- Types    - hidden internal data types
 +---- Process  - implementation of the event types.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
