### ISSUE TITLE
HALON-636: Add time measure to leveldb writes

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1214]
*Created by: Fuuzetsu*

We don't have a metric system nor a sane way to log this. Just add
traceEventIO around the call and make it possible to enable. We can then
advise users with RC expiries to enable eventlog

```
-  Ghc-Options: -threaded -Wall "-with-rtsopts=-C0 -T" -rtsopts -g -Werror
+  Ghc-Options: -threaded -Wall -eventlog "-with-rtsopts=-C0 -T -l-au"
-rtsopts -g -Werror
```

and we can analyse the log to see if writes are the issue.

-----

I'm open to better suggestions for timing this.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
