### ISSUE TITLE
HALON-642: Figure out what happens with PSStarting

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1219]
*Created by: Fuuzetsu*

We *always* failed a notification for a PSStarting process that went out
to that process. This was masked because

* we only subsequently fail PSOnline processes
* ruleProcessStart waits for notification set to come through
* notification set is sent to RC even if failure occurs
* worse, in current scenario, we never would actually fail any
  processes: some dead code removal recently was removed without
  understanding why it was dead; while it actually *was* dead, updated
  code should have replaced it

Now we only notify PSOnline processes to begin with and actually notify
RC about processes that we failed to deliver to. Sprinkle some comments
here and there.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
