### ISSUE TITLE
HALON-644: Bound node <-> mero channel relation

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1221]
*Created by: Fuuzetsu*

For whatever misguided reason, we had an unbounded node -> mero channel
relation. This caused the behaviour where often after halond restart we
would see a process fail PSStarting notification. Debugging showed this
notification was failing for the halon:m0d process on the same node.
What was happening was:

* halond restarts
* halon:m0d starts up and connects up its channel
* we request halon:m0d reconnect (we don't know if halond restarted or
  we had a network failure so we always ask)
* new halon:m0d starts and connects up its channel
* m0d process PSStarting notification sent out
* the first, no longer active mero channel is used
* current halon:m0d processes never receive notification
* timeout
* recovery failure

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
