### ISSUE TITLE
[HALON-650] Introduce `GraphLike` in preparation for updating graph

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1227]
*Created by: nc6*

Introduces `GraphLike` from RFC019.

In order to specify this in a nice way, we need to use `TypeFamilyDependencies`, requiring GHC8. So this PR also ports to GHC8.

Best to review commit-by-commit; I have tried to make them independent and meaningful.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
