### ISSUE TITLE
CASTOR-2443: Drop service reconnect.

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1251]
*Created by: Fuuzetsu*

After removal of channels, the only purpose reconnect served was to
trigger STARTED event from mero. However it also turned out to be
harmful, causing a race. Instead of dealing with reconnect and the logic
there, just ask the service to send this event itself. If it's ready and
alive, it will send a message to RC and RC will be none-the-wiser that
it wasn't mero that sent the message.

Note that I've seen issues in case of dropped network connection but am
unable to determine in short-term if it's because of my testing method
or not. Rebooting a node however lets us recover without exhibiting
CASTOR-2443 which is currently a blocker. I therefore suggest merging
this ASAP and testing and fixing (if needed) network drop afterwards.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
