### ISSUE TITLE
HALON-698: Fix stack 1.4.0 warnings and more.

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1257]
*Created by: Fuuzetsu*

From stack-1.4.0, packages with `custom` `build-type` but without
`custom-setup` show a warning. This looked ugly and made jenkins spew a
bunch of extra logs. Also fix any other warnings in our packages and
their tests. Set `-Werror` everywhere and remove `maintainer` flag.
Remove remains of `mero` flag: our CI can build it and only runs the
tests it knows how to run anyway. We may need to fix things up in Castor
`circle.yml` after merging.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
