### ISSUE TITLE
HALON-675: Support controlling SNS from halonctl.

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1258]
*Created by: nc6*

This patch has been deliberately designed to not touch anything
outside of `halonctl`, in order to make it easy to justify porting
back to teacake to help with some of the issues we see there with
repair or rebalance getting stuck.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
