### ISSUE TITLE
Allow same version halond and state in any format

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1267]
*Created by: Fuuzetsu*

This accomodates the case on clusters where RE-built halon has UNKNOWN
version as does the state.

Further, introduce a hack that will kill halond on the node if RC exits
with ReallyDie exception as a stop-gap to prevent RS restarting it and
looping forever.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
