### ISSUE TITLE
HALON-690: Support process multiplicity

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1278]
*Created by: nc6*

This gives a much easier way to handle process multiplicity, as is needed for s3server (e.g. they want to create multiple processes for s3server).

In addition, to facilitate this, we create a proper encoding of LNET addresses and endpoints.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
