### ISSUE TITLE
[HALON-668] hctl: Show aligned filesystem stats values

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1287]
*Created by: vvv*

Before:

    Filesystem stats:
      Total space: 4741643894784
      Free space: 4741643894784
      Total segments: 1075833184
      Free segments: 1075389596

After:

    Filesystem stats:
      Total space:    4,741,643,894,784
      Free space:     4,741,643,894,784
      Total segments:     1,075,833,184
      Free segments:      1,075,389,596

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
