### ISSUE TITLE
[HALON-671] Improve resilience of repair/rebalance abort

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1289]
*Created by: vvv*

Don't loop indefinitely if status of SNS repair/rebalance abort request does not arrive. Instead,
1. Call sns_repair_abort.
2. Call sns_repair_status finite number of times until all services report as IDLE, PAUSED, or FAILED.
3. If this fails after n attempts (n=5), repeat steps 1-2 for m attempts (m=10).
4. If we have tried >m times, fail and restart the process(es). Mark the repair as aborted in this case.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
