### ISSUE TITLE
Reduce noisiness of decision log entries

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1294]
*Created by: vvv*

- Don't print '>' (phase entry) lines. They are implied as nothing can be logged until some phase is entered.
- Don't print headings for Rule, SM, and Phase contexts. They apply to every decision log entry, so printing them is a waste of space.
- Insert a blank line at the end of a decision log entry.
- [refactor] Delete unneeded `fillSep`.
- Align imports.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
