### ISSUE TITLE
[HALON-727] rcRules: Increase buffer capacity

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1300]
*Created by: vvv*

HALON-727 bug was caused by insufficient capacity of CEP machine's buffer
(Bounded 64). `fifoBuffer' is implemented in such a way, that insertion
of a new element into already full buffer (of Bounded type) drives out
the oldest (leftmost) element.

Revert commit bc3c80464c89f132df211761f991ebe132398e7c --- restore
CEP machine's buffer original capacity (64 -> 4096).

+ Network.CEP.Buffer (fifoBuffer): Write a warning to stderr whenever
  insertion into already full buffer discards an element.

Lots of kudos to Maxim Medved! Without his help and expertise this bug
would still remain undiscovered.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
