### ISSUE TITLE
Set formulaic pver fid carefully

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1302]
*Created by: vvv*

Rename `mkVirtualFid` to `mkPVerFormulaicFid`. Original name was misleading, because the resulting fid is of formulaic, not virtual, kind.

Move `mkPVerFormulaicFid` to a more suitable place.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
