### ISSUE TITLE
CEP (rcRules): Use `Unbounded` buffer

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1307]
*Created by: andriytk*

When new message is added into a *full* Bounded buffer, the oldest
message of that buffer is discarded (see fifoBuffer.go.Insert).
Use Unbounded buffer, because we prefer running out of memory to
losing messages.

(cherry picked from commit be1ba4e8872ca5ed07e81299587654247d7d1e52)

Conflicts:
	mero-halon/src/lib/HA/RecoveryCoordinator/CEP.hs

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
