### ISSUE TITLE
Refactor `parseInitialData` using `ExceptT`

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1315]
*Created by: vvv*

- `parseInitialData`: get rid of the cascade of Either cases.
- `validateInitialData`: check that rack indices are unique.
- Fix a bug in `InitialData` validation logic: `any (not . null) encl_ids` returns True if at least one of the enclosure identifiers is non-empty. The proper check is `all (not . null) encl_ids` or `not (any null encl_ids)` --- return True iff neither of identifiers is empty.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
