### ISSUE TITLE
scripts/h0: Pass options to 'rebuild' and 'make' commands

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1325]
*Created by: vvv*

Building Halon afresh (after `git clean -fdx && rm -rf .stack-work`):
- `h0 rebuild` - 19m39s;
- `h0 rebuild --fast` - 10m.

Compiling after changing one datatype definition in Castor/Initial.hs:
- `h0 make` - 10m3s;
- `h0 make --fast` - 3m49s.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
