### ISSUE TITLE
rfc/025-multiple-pools.md: s/host/controller/; revise role specs

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1327]
*Created by: vvv*

* Rename `enc_hosts` to `enc_controllers`. "Controller" is how that piece of equipment is called. Let facts configuration use the same terminology.

* Revise role specification:
  - bare `c_halon_address` and `c_halon_roles` would look nice in YAML file, but would require special treatment in Haskell code. It is not worth it;
  - add `r_` prefix to the fields of role descriptor.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
