### ISSUE TITLE
scripts: add h0s

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1333]
*Created by: chumakd*

This is a helper script for running Halon and Mero in a development
environment on multiple machines. It provides several commands that
abstract common routine tasks which have to be performed in order to
test Mero and Halon together when they are built in their source
directories.

Assuming that a user has already built Mero and Halon, for example by
running `m0 make` and `h0 make`, they can now start Halon and Mero on
their local cluster with the help of `h0s` script. The following example
demonstrates a typical sequence of commands:

  # this has to be done only once, after a cluster is created
  h0s scankeys cmu.local,ssu1.local,ssu2.local,client1.local

  # bring Halon services up on all hosts
  h0s up -c cluster.yml cmu.local,ssu1.local,ssu2.local,client1.local

  # do usual Halon stuff
  halonctl mero bootstrap
  halonctl mero status
  # --> run some tests here <--
  halonctl mero stop

  # completely remove Halon+Mero meta-data and services on all hosts
  h0s destroy cmu.local,ssu1.local,ssu2.local,client1.local

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
