### ISSUE TITLE
s/CST_MGS/CST_CONFD/

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1335]
*Created by: vvv*

`M0_CST_MGS` has been renamed to `M0_CST_CONFD` in Mero source code.
Update Halon sources correspondingly.

**Note:** Should be landed together with Mero patch [c/16976](http://gerrit-sage.dco.colo.seagate.com:8080/16976).

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
