### ISSUE TITLE
[HALON-759] visualize-schema: Visualize relation cardinalities

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1342]
*Created by: vvv*

Use DOT arrow styles to represent cardinalities:

    CardinalityFrom | CardinalityTo | arrowhead | arrowtail
    ----------------|---------------|-----------|----------
    AtMostOne       | AtMostOne     | normal    | none
    AtMostOne       | Unbounded     | onormal   | none
    Unbounded       | AtMostOne     | normal    | oinv
    Unbounded       | Unbounded     | onormal   | oinv

HA.Resources.TH:
- add `cardinalities` function;
- [refactoring] extract `conTs` function;
- [refactoring] use `DecsQ` and `ExpQ` aliases for the sake of uniformity.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
