### ISSUE TITLE
scripts/install-halon-services: use new default role file for halonctl

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1345]
*Created by: chumakd*

Since `halonclt` has switched to the proper default role file, which is
'/etc/halon/mero_role_mappings', instead of hard-coded
'/etc/halon/role_maps/prov.ede', it doesn't make sense to create a fake
'prov.ede' any more. This script now sets up 'mero_role_mappings'.

[skip ci]

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
