### ISSUE TITLE
mero-halon: rename Enclosure_XXX1 back to Enclosure

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1346]
*Created by: andriytk*

As appeared (from vvv): "Distinct types are justified if the payload differs".

See more at https://seagate.slack.com/archives/C0GLUEP2T/p1515671743000269.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
