### ISSUE TITLE
HA.Resources, HA.Resources.Castor: Use GeneralizedNewtypeDeriving

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1352]
*Created by: vvv*

* `GeneralizedNewtypeDeriving` extension is already enabled in halon.cabal,
  there is no need to specify it in .hs files explicitly.
* Derive `Hashable` and `ToJSON` for newtypes automatically and remove
  `instance` definitions.
* HA.Resources.Castor: Use implicit import list instead of qualified.
* Sort identifiers in the `deriving` lists (with exception of FromJSON
  and ToJSON, which go to the end of the list).

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
