### ISSUE TITLE
scripts/h0: use --extra-lib-dirs instead of LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#1405]
*Created by: chumakd*

* let 'stack' utlity be aware of a custom library path when executing
  `h0 make|rebuild` for the greater good
* build all Halon modules, not only mero-halon, the same way as it's
  done when building rpm

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
