### ISSUE TITLE
Initial stab at RFC for node agent.

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#28]
*Created by: mboes*

According to the template at

https://docs.google.com/a/tweag.io/document/d/1eFKseC_cR3pAXEoa12u4AfcGN2tS1kMgr-RJrbavpJg/edit

This is an HLD, intentionally not specifying API's in code form. That
would be duplicating whatever API's ultimately end up in the code, and
so should gainfully be introduced on a branch in a Haskell source file.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
