### ISSUE TITLE
improve halon unit file and build system.

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#723]
*Created by: qnikst*

1. Add +RTS -s -RTS by default so halon will dump it's GC stats
   at exit.
2. Change kill signal to SIGINT, so halon will dump it's stats
   and eventlog if started with that.
3. Change restart rule to on-abort, otherwise halon is restarted
   even if systemctl stop was called..
4. Set +RTS -A16m -RTS to have bette GC stats by default
5. Compile halon with -rtsopts by default.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
