### ISSUE TITLE
Dev/another version

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#752]
*Created by: bmac423*

I un-did the rpmrel things. I think assigning git version via Makefile, like @nc6 did initially, is cleaner. Using a common source for rpm version makes more sense than alternate paths depending on build environment, so keeping git describe as the common source of truth is best. I also removed the cut from the version determination and added the --define parameter to mock rebuild to address the interpolation issue.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
