### ISSUE TITLE
Halon-242: Adjust for k=0 case.

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#755]
*Created by: nc6*

Since Mero patch c/10644 landed, Mero supports 0 parity units for
MDPool. This change thus effects:
- Set K=0 for MDpool PVer.
- Consistently select one drive per ios, even in single ios case.

Then:
N=P=#disks=#ioservices
failure vector=[0,0,0,x,1], where x is 0 in 1 ios case and 1 otherwise.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
