### ISSUE TITLE
Fix deserialisation for empty InternalObjectStateChange

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#761]
*Created by: Fuuzetsu*

Bug triggered by trying to notify mero with a `Set []` which would
then have halon generate `InternalObjectStateChange []` which would
then be serialised and sent through RC then deserialised, upon which
halon would fail as it's using `some`, expecting at least one element
in the list: there is no reason for this assumption except that maybe
we shouldn't be sending out an empty message at all to begin with.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
