### ISSUE TITLE
HALON-179: Deal with metadata drive failures

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#771]
*Created by: nc6*

This PR:
- Updates the SSPL schema and bindings in line with recent SSPL changes.
- Fixes an issue in `ruleResetAttempt`
- Implements failure handling for metadata drives.
- Updates the test framework to support non-Mero drives.
- Adds a new test for metadata drive failures.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
