### ISSUE TITLE
HALON-291: Fix RG update with incorrect service pid.

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#794]
*Created by: qnikst*

Removed an old rule that allowed receiving out of order service
start messages. This rule is no longer needed because service
start rule is written in a way that it will return service start
logic in case of RC death and message can't come out of order.

In case if it was out of protocol message then this will be caught
by the local monitor.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
