### ISSUE TITLE
Check if repair is on-going before starting it

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#800]
*Created by: Fuuzetsu*

While it's not a fix for the issue we saw a while ago (as this is fixing new-to-master code anyway), it unblocks further investigation with repair.

Halon now stays responsive though I do not see the repair complete on dev VM (cluster not tried).

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
