### ISSUE TITLE
halon.spec: reuse built snapshot in /stack if it exists.

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#848]
*Created by: mboes*

Fixes HALON-266.

The castor build system prebuilds the snapshot packages before calling
mock. But the Halon spec file did not know about this, so the prebuilt
snapshot packages were not reused.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
