### ISSUE TITLE
Inhibit normal RAID failure handling when reassembly is taking place

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#853]
*Created by: nc6*

While testing expander reset, sometimes the normal RAID message would come in and kick of a reset while reassembly was taking place. This PR adds a resource to track reassembly and inhibits reset when it's ongoing.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
