### ISSUE TITLE
Make it easier to override Version.hs.

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#858]
*Created by: nc6*

[This PR consolidates the changes and rebases them onto master, dropping the change to versioning, since this isn't really related to the other changes]

Instead of monkey patching of the version file using sed, which can be
brittle, we instead ask that tools dump a .hs file with all the
version info as they want it. This is used by the Castor build system,
and this method is easier than the alternative.

This patch also replaces the "built on" line with a "authored on" line.
The reason for this is that castor's nix based build procedure resets
the current date to the epoch anyways, so "built on" won't tell you much
at all. Making build artifacts not build on current time furthermore
helps make the build result more deterministic.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
