### ISSUE TITLE
HALON-309: Implement keepalive mechanism for SSPL-HL.

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#891]
*Created by: qnikst*

Currently amqp library may silently loose connection to rabbit-mq.
In this case halon will not reply to SSPL-HL requests. In order to
fix this problem we eventually send explicit keepalive messages to
the halon exchange, in this case if HALON does not see keepalive
in TIMEOUT seconds it restarts connection.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
