### ISSUE TITLE
WIP: Only start using a drive once it's ready.

### ISSUE THREAD

**Issue by root** [Seagate/halon#892]
*Created by: nc6*

To be ready, a device should be present, powered and
visible to the operating system. At this point (and not before)
we may mark it as visible to Mero, attach it, and potentially
start rebalance operations.

We also move from calling `handleRepairInternal` directly and
rely on state transitions and `PoolRebalanceRequest`.

Logic should now be: rules handling SSPL-level failures should
firstly be concerned with updating the state in the graph. Once
this is done, they can call 'checkAndHandleDriveReady' to trigger
any Mero related operations.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
