### ISSUE TITLE
cep: Drop dependency on ghc-datasize in profiling builds.

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#908]
*Created by: facundominguez*

ghc-datasize depends on ghc-heap-view which doesn't build with profiling enabled.

A custom Setup.hs file in cep would give a better user experience (no need to figure out the ghc-heap-view error), but using a flag in `cep.cabal` is simpler to maintain.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
