### ISSUE TITLE
[HALON-377] Identify node and controller states.

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#912]
*Created by: nc6*

This PR does three things:
- Synchronise node/controller states as we already have for disk/sdev.
- Add corresponding cascade rules to cascade all states.
- Introduce `StateCascadeInclude` to simplify this sort of 'phantom rule'.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
