### ISSUE TITLE
[HALON-397] Fix decision-log halon role for hctl boostrap cluster

### ISSUE THREAD

**Issue by root** [Seagate/halon#924]
*Created by: Fuuzetsu*

The file path would parse poorly and logs would go into a black-hole
somewhere (or maybe file called \"…\") though I couldn't locate it.

---

When checking that this works, I noticed that we don't wait for stations to be ready before running satellites or for either to be ready before trying to start services. I have before seen that if we try to start satellite too fast before station is ready, things might go wrong (node doesn't join cluster). Might want to block somehow there.

Other than that, everything seems to work fine (or no worse than "traditional" method) and also starts services using halon roles so it's probably worthwhile moving to this method.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
