### ISSUE TITLE
Updates to halon interfaces to mero

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#93]
*Created by: facundominguez*

This is the latest work done on bringing halon in synch with Mero.

Tests for rpclite, confc and the notification interface were passing with the mero from 3 weeks ago plus a few patches for issues discovered along the process.

The patches to mero are in the alpha cluster in /home/facundo/mero.

confc and notification interface tests require starting confd with the st script provided with mero.

```
sudo mero/m0t1fs/linux_kernel/st/st sstart
```

The rpclite and network-transport-rpc tests require only loading the m0mero kernel module.

`make test` should work in the confc and network-transport-rpc folders.
`make testhastate` and `make testepoch` should work in the mero-halon folder.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
