### ISSUE TITLE
Calculate tolerable controller failures

### ISSUE THREAD

**Issue by 1468ca0b-2a64-4fb4-8e52-ea5806644b4c** [Seagate/halon#946]
*Created by: nsahasra-seagate*

- Modified the logic to calculate the failure tolerance
  for controllers in the case of preloaded pool versions.
- This change is temporary, under assumption that failures
  at levels higher than that of controller are not tolerable.
- The complete fix will be landed with HALON-406.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
