### ISSUE TITLE
HALON-413: Fail node on Mero BE error

### ISSUE THREAD

**Issue by root** [Seagate/halon#954]
*Created by: nc6*

We now have an additional message type from Mero, which is sent when the metadata back end throws an error. This should be treated as a node level failure. 

Currently we fail the node as per any other circumstance, which should trigger a restart. We also log an IEM about the BE error, as this could indicate e.g. a totally failing RAID pair.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
