### ISSUE TITLE
halon: Have the RG use safecopy for serialization.

### ISSUE THREAD

**Issue by root** [Seagate/halon#959]
*Created by: facundominguez*

Castor CI succeeded with an unsquashed version of this PR
https://circleci.com/gh/seagate-ssg/castor/1468

This PR addresses the RG side of goal (1) of
https://jira.xyratex.com/browse/HALON-343

@qnikst is working on addressing goal (0) of the EQ side.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
